strategy:
  matrix:
    Linux:
      imageName: 'ubuntu-16.04'
    Mac:
      imageName: 'macos-10.13'
    Windows:
      imageName: 'vs2017-win2016'

steps:
- script: dotnet restore
  displayName: 'Restore'
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: publish
    projects: '**/*.csproj'
    arguments: '--configuration Release'
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
