strategy:
  matrix:
    Linux:
      imageName: 'ubuntu-latest'
      artifactName: 'linux'
    Mac:
      imageName: 'macos-latest'
      artifactName: 'macos'
    Windows:
      imageName: 'windows-latest'
      artifactName: 'windows'

pool:
  vmImage: $(imageName)

steps:
- script: dotnet restore
  displayName: 'Restore'
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    publishWebProjects: False
    zipAfterPublish: False
    projects: '**/*.csproj'
    arguments: '-c Release -o $(Build.ArtifactStagingDirectory) -p:PublishSingleFile=true'
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    artifactName: '$(artifactName)'
